#!/bin/bash

wmake libso libraries/customFunctions

wmakeLnInclude libraries/customTurbulenceModels/turbulenceModels
wmake libso libraries/customTurbulenceModels/compressible

wmake libso libraries/aerosolThermo
wmake libso libraries/aerosolModels

wmake applications/solvers/aerosolEulerFoam

