#!/bin/bash

wclean libraries/customFunctions

wcleanLnIncludeAll libraries/customTurbulenceModels/turbulenceModels
wclean libraries/customTurbulenceModels/compressible

wclean libraries/aerosolThermo
wclean libraries/aerosolModels

wclean applications/solvers/aerosolEulerFoam
