#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

wclean solvers/aerosolEulerFoam

wclean utilities/bentPipeDeform
wclean utilities/sampleDropletFlux
wclean utilities/sampleAspirationWedge

# ----------------------------------------------------------------- end-of-file
