#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}

for lib in */ ; do
    wclean $makeType $lib
done

# ----------------------------------------------------------------- end-of-file

