#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions
. ../../../scripts/AeroSolvedRunFunctions

checkPython3

# Params

SIGMA=1.0001
DCM=1.2E-5
VGZ=1.085e-9
RHOVGL=1.258E3

YMIN=1E-13
YMAX=1E-10

MATH="import math as m"

# Configure

case $1 in

    moment)

        MODEL=twoMomentLogNormalAnalytical

        CMD=$(echo "$MATH; print($DCM*m.exp(-0.5*m.log($SIGMA)**2))" | python3)
        DM=$(echo "$MATH; print($CMD*m.exp(1.5*m.log($SIGMA)**2))" | python3)

        M=$(echo "$MATH; print($VGZ/(1.0/6.0*m.pi*$RHOVGL*($DM)**3))" | python3)

        N=1 #Dummy

        rm -f 0; cp -r 0.org 0

        m4 -DVARM=$M -DVARMNAME="M" 0/M.m4 > 0/M

        ;;

    sectional)

        MODEL=fixedSectional

        SECTIONSPERDECADE=8

        N=$(echo "$MATH; print(int(m.log10($YMAX/$YMIN)*$SECTIONSPERDECADE))" | python3)

        rm -f 0; cp -r 0.org 0

        cat sections.txt | while read DATA; do

            I=$(echo $DATA | cut -d " " -f 1)
            XI=$(echo $DATA | cut -d " " -f 2)
            MI=$(echo $DATA | cut -d " " -f 3)

            m4 -DVARM=$MI -DVARMNAME="M.$I" 0/M.m4 > 0/M.$I

        done

        ;;
    *)
        echo "Invalid aerosol model specified (sectional or moment)"
        exit 1
        ;;
esac

VARS="\
    -DVARMODEL=$MODEL \
    -DVARN=$N \
    -DVARYMIN=$YMIN \
    -DVARYMAX=$YMAX \
    -DVARSIGMA=$SIGMA \
    -DVARVGZ=$VGZ \
    "

m4 $VARS constant/aerosolProperties.m4 > constant/aerosolProperties
m4 $VARS 0/VG.dispersed.m4 > 0/VG.dispersed

find 0 -name "*.m4" -exec rm {} \;

runApplication blockMesh

runApplication $(getApplication)
