#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions
. ../../scripts/AeroSolvedRunFunctions

checkPython3

U0=1

if ! [[ $1 =~ ^([0-9]+) ]]; then
    echo "Invalid sampling ratio number"
    exit 1
else
    R=$1
fi

if ! [[ $2 =~ ^(fullStokes|Manninen)$ ]]; then
    echo "Invalid inertial model (fullStokes or Manninen)"
    exit 1
else
    INERTIALMODEL=$2
fi

echo $R > R.txt

U=$(echo "print($U0/$R)" | python3)

cp -r 0.org 0

VARS="\
    -DVARU=$U \
    -DVARINERTIALMODEL=$INERTIALMODEL \
    "
setMacros "$VARS"

rm -f 0/*.m4

runApplication blockMesh

runApplication topoSet -latestTime

runApplication $(getApplication)

#runApplication python3 plot.py
