#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions
. ../../scripts/AeroSolvedRunFunctions

cp -r 0.org 0

rm -f 0/*.m4

runApplication blockMesh

runApplication $(getApplication)
